
export const all_routes = {
   
   
   
    //Home Modules
    homeone: "/index",
    hometwo:"/index-2",
    homethree:"/index-3",
    homefour:"/index-4",
    homefive:"/index-5",
    homesix:"/index-6",

    //Course Modules
    courseGrid:"/course/course-grid",
    courseList:"/course/course-list",
    courseDetails:"/course/course-details/:courseSlug",
    courseDetails2:"/course/course-details-2",
    courseCategory:"/course/course-category",
    courseCategory2:"/course/course-category-2",
    courseCategory3:"/course/course-category-3",
    courseResume:"/course/course-resume",
    courseWatch:"/course/course-watch",
    courseCart:"/course/cart",
    courseCheckout:"/course/checkout",

    //Admin Modules
    adminDashboard:'/admin/admin-dashboard',
    adminInstructorList:'/admin/instructor-list',
    adminInstructorRequests: '/admin/instructor-requests',
    adminProfile:'/admin/admin-profile',
    adminCourse:'/admin/admin-course',
    adminCourseGrid:'/admin/admin-course-grid',
    adminCourseDetails:"/admin/admin-course/:courseSlug",
    adminAnnouncements:'/admin/admin-announcements',
    adminAssignment:'/admin/admin-assignment',
    adminQuiz:'/admin/admin-quiz',
    adminQuizResult:'/admin/admin-quiz-results/:quizId',
    adminCertificate:'/admin/admin-certificate',
    adminEarning:'/admin/admin-earnings',
    adminPayout:'/admin/admin-payout',
    adminStatements:'/admin/admin-statements',
    adminMessage:'/admin/admin-message',
    adminTickets:'/admin/admin-tickets',
    adminChangePassword:'/admin/admin-change-password',
    adminPlan:'/admin/admin-plans',
    adminSocialProfiles:'/admin/admin-social-profiles',
    adminLinkedAccounts:'/admin/admin-linked-accounts',
    adminNotification:'/admin/admin-notifications',
    adminIntegrations:'/admin/admin-integrations',
    adminWithdraw:'/admin/admin-withdraw',
    adminWishlist:'/admin/admin-withdraw',
    adminReviews:'/admin/admin-withdraw',
    adminQuizAttempts:'/admin/admin-withdraw',
    adminOrders:'/admin/admin-withdraw',
    adminChat:'/admin/admin-withdraw',
    adminReferral:'/admin/admin-withdraw',
    adminQA:'/admin/admin-quiz-questions/:quizId',
    adminsettings:'/admin/admin-settings',
    adminCreateNewCourse:'/admin/create-course/:courseId',
    adminCourseSyllabus:'/admin/course-syllabus/:courseId',
    adminCourseAccreditation:'/admin/course-accreditation/:courseId',
    adminCoursePricing:'/admin/course-pricing/:courseId',
    adminCourseSEO:'/admin/course-seo/:courseId',
    adminCourseReview:'/admin/course-review/:courseId',
    adminStudentsGrid:'/admin/students',
    adminStudentsList:'/admin/student-list',
    adminStudentProgress:'/admin/student-progress',
    adminInstructorsList:'/admin/instructor-list',
    adminCourseReviews:'/admin/course-reviews',
    adminCategories:'/admin/categories',
    adminSpecialties:'/admin/specialties',
    adminPayouts:'/admin/payouts',
    adminRevenueReports:'/admin/revenue-reports',

    messageDetailPage:'/messages/:conversationId',
    adminCertificateBuilder:'/admin/certificate-builder',
    adminCertificateBuilderId:'/admin/certificate-builder/:templateId',



    //Instructor Modules
    instructorDashboard:'/instructor/instructor-dashboard',
    instructorProfile:'/instructor/instructor-profile',
    instructorCourse:'/instructor/instructor-course',
    instructorCourseDetails:"/instructor/instructor-course/:courseSlug",
    instructorCourseGrid:'/instructor/instructor-course-grid',
    instructorAnnouncements:'/instructor/instructor-announcements',
    instructorAssignment:'/instructor/instructor-assignment',
    instructorQuiz:'/instructor/instructor-quiz',
    instructorQuizResult:'/instructor/instructor-quiz-results/:quizId',
    instructorEarning:'/instructor/instructor-earnings',
    instructorPayout:'/instructor/instructor-payout',
    instructorStatements:'/instructor/instructor-statements',
    instructorMessage:'/instructor/instructor-message',
    instructorTickets:'/instructor/instructor-tickets',
    instructorChangePassword:'/instructor/instructor-change-password',
    instructorPlan:'/instructor/instructor-plans',
    instructorSocialProfiles:'/instructor/instructor-social-profiles',
    instructorLinkedAccounts:'/instructor/instructor-linked-accounts',
    instructorNotification:'/instructor/instructor-notifications',
    instructorIntegrations:'/instructor/instructor-integrations',
    instructorWithdraw:'/instructor/instructor-withdraw',
    instructorWishlist:'/instructor/instructor-withdraw',
    instructorReviews:'/instructor/instructor-withdraw',
    instructorQuizAttempts:'/instructor/instructor-withdraw',
    instructorOrders:'/instructor/instructor-withdraw',
    instructorChat:'/instructor/instructor-withdraw',
    instructorReferral:'/instructor/instructor-withdraw',
    instructorQA:'/instructor/instructor-quiz-questions/:quizId',
    instructorsettings:'/instructor/instructor-settings',
    instructorCreateNewCourse:'/instructor/create-course/:courseId',
    instructorCourseSyllabus:'/instructor/course-syllabus/:courseId',
    instructorCoursePricing:'/instructor/course-pricing/:courseId',
    instructorCourseSEO:'/instructor/course-seo/:courseId',
    instructorCourseReview:'/instructor/course-review/:courseId',


    studentDashboard:'/student/student-dashboard',
    studentProfile:'/student/student-profile',
    studentsGrid:'/instructor/students',
    studentsDetails:'/instructor/students-details',
    studentsList:'/instructor/student-list',
    studentOrderHistory:'/student/student-order-history',
    studentMessage:'/student/student-messages',
    studentCourses:'/student/student-courses',
    studentCertificates:'/student/student-certificates',
    studentReviews:'/student/student-reviews',
    studentWishlist:'/student/student-wishlist',
    studentQuiz:'/student/student-quiz',
    studentQuizResult:'/student/student-quiz/results/:attemptId',
    studentQuizQuestion:'/student/student-quiz-questions/:quizId',
    studentReferral:'/student/student-referral',
    studentTickets:'/student/student-tickets',
    studentSettings:'/student/student-settings',
    studentChangePassword:'/student/student-change-password',
    studentSocialProfile:'/student/student-social-profile',
    studentLinkedAccounts:'/student/student-linked-accounts',
    studentNotification:'/student/student-notifications',
    studentBillingAddress:'/student/student-billing-address',

    courseLearningPage:'/learn/:courseSlug/:lessonId?',
    courseDemoPage:'preview/:courseSlug/:lessonId?',
    resumeCourses: '/resume/courses',

    verify:'/verify-email',
    login:'/login',
    googlelogin:'auth/google/success',
    register:'/register',
    forgotpassword:'/forgot-password',
    setpassowrd:'/set-password',
    otp:'/otp',
    lockscreen:'/lock-screen',
    privacyPolicy: "/pages/privacy-policy",
    termsConditions: "/terms-conditions",
    contactUs: "pages/contact-us",
    about_us: "/pages/about-us",
    invoices: "/pages/invoices",
    FAQ: "/pages/faq",
    pricingPlan: "/pages/pricing-plan",
    Error404: "/pages/error-404",
    Error500: "/pages/error-500",
    underconstruction: "/pages/under-construction",
    comingSoon: "/pages/coming-soon",
    becomeAnInstructor: "/pages/become-an-instructor",
    instructorList:'/pages/instructor-list',
    instructorGrid:'/pages/instructor-grid',
    instructorDetails:'/pages/instructor-details/:id?',
    testimonials:'/pages/testimonials',
    


    blogGrid: "/blog/blog-grid",
    blogGrid2: "/blog/blog-2-grid",
    blogGrid3: "/blog/blog-3-grid",
    blogDetails: "/blog/blog-details",
    blogCarousal: "/blog/blog-carousal",
    blogMasonry: "/blog/blog-masonry",
    blogLeftSidebar: "/blog/blog-left-sidebar",
    blogRightSidebar: "/blog/blog-right-sidebar",
    blogDetailsLeftSidebar: "/blog/blog-details-left-sidebar",
    blogDetailsRightSidebar: "/blog/blog-details-right-sidebar",

};
